dist: trusty
language: ruby
before_install:
        - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
        - pdflatex -interaction=nonstopmode -halt-on-error leonardi_M2FSI_rapport_stage_2017.tex
#deploy:
#        file:
#                - *.pdf 
