= Rapport de stage

Rapport de mon stage chez http://www.alter-solutions.com/[Alter Solutions Engineering]

Du 10 avril 2017 au 30 septembre 2017

Stage de fin d'étude de http://masterinfo.univ-mrs.fr/FSI.html[master FSI].

https://www.overleaf.com/latex/templates/climate-policy-initiative-report-template/kjfjzrcjgtqg#.WTVoYKJVtv0[Le template est l'oeuvre d'Andrew Hobbs disponible sous licence Creative Commons.]

.TODO List
* Changer screenshot de ZAP par 1 pris en cours d'utilisation sur DVWA (par exemple) => plus réaliste
* Modifier le style des listings, notamment police monospacet ! Augmenter l'interligne
* Voir si je peux faire une référence au listing
* Changer les footnotes pour des notes en fin de rapport
* Vérifier que tous les acronymes sont expliqués lors de leur première apparition (et pas après)
* Vérifier que tous les logiciels/frameworks/etc ont un lien lors de leur première apparition (et pas après)
* Concordance des temps
* Retaper pour que ce soit moins verbeux
* Vérifier capitalisation des mots (e.g. git en minuscules sauf début de phrase)
* Faire concorder les couleurs
* "push" et autres anglicismes => tout mettre en italique ou tout enlever